### ISSUE TITLE
Request for Fedora RPM package

### ISSUE THREAD

**Issue by qomarhsn** [NabilSnigdho/obk-layout-editor#2]
👋 Hello @NabilSnigdho,

First and foremost, thank you for developing the amazing OBK Layout Editor! I have been using it on Debian and Arch Linux by downloading the DEB package and Arch package build, and it has been instrumental in creating layouts for the Open Bangla Keyboard. Your tool has made the experience so much easier and efficient.

Recently, I have migrated to Fedora as my daily driver, and I would love to continue using the OBK Layout Editor. However, I noticed that there is no RPM package available in the GitHub Releases page. 😔

Therefore, I kindly request you to consider publishing an RPM package for the OBK Layout Editor, specifically tailored for Fedora. This would greatly benefit Fedora users who wish to utilize your fantastic tool without having to go through manual installation processes.

Thank you for your consideration, and I hope my request can be taken into account. If there are any updates or plans regarding the availability of an RPM package, I would be glad to know.

Keep up the excellent work! 💪

Best regards,
Kamrul Hasan

**Comment by NabilSnigdho** [comment]
@kamrulhasanio Thanks for using the app and your kind words. Just added an RPM package in the latest release, please let me know if it works on fedora.

**Comment by qomarhsn** [comment]
@NabilSnigdho! 🎉 I installed the RPM package on Fedora, and I'm happy to report that the OBK Layout Editor is working flawlessly! 👌 Thank you so much for considering my request and quickly adding the RPM package to the latest release.
